"""Forcing migration detection

Revision ID: 4cf69eaa05ab
Revises: 62466f028378
Create Date: 2024-10-03 21:22:17.507610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf69eaa05ab'
down_revision = '62466f028378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_column', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dummy_column')

    # ### end Alembic commands ###
