"""Adding User Table

Revision ID: 62466f028378
Revises: a06988edb5aa
Create Date: 2024-10-03 20:49:33.682927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62466f028378'
down_revision = 'a06988edb5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_userid_users'), 'users', ['userid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_userid_users'), type_='foreignkey')
        batch_op.drop_column('userid')

    op.drop_table('users')
    # ### end Alembic commands ###
