"""Add MFA columns to User model

Revision ID: edeff83ba16b
Revises: 4cf69eaa05ab
Create Date: 2024-12-09 08:21:56.269078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edeff83ba16b'
down_revision = '4cf69eaa05ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_key', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('mfa_key')

    # ### end Alembic commands ###
